services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/api_caller:latest
    command: bash
    volumes:
      - $PWD:/workdir
    networks:
      - geci
    depends_on:
      eradication_progress:
        condition: service_healthy
    profiles:
      - apis

  eradication_progress:
    image: islasgeci/eradication_data_requirements:latest
    entrypoint:
      [
        "uvicorn",
        "eradication_data_requirements.api:api",
        "--host",
        "0.0.0.0",
        "--port",
        "10000"
      ]
    volumes:
      - $PWD/tests/data:/workdir/data
    networks:
      - geci
    healthcheck:
        test: ["CMD", "curl", "-f", "http://eradication_progress:10000/docs"]
        interval: 2s
        timeout: 2s
        retries: 5

networks:
  geci:
    name: internal_api_caller
